"""
uploader/metadata_builder.py — YouTube 업로드 메타데이터 구성

pipeline.state를 받아 YouTube videos.insert API body dict를 반환한다.
제목, 설명, 태그, 카테고리ID, 공개 설정을 한/영 각각 구성한다.
"""

import logging
import re
from typing import Any

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────
# 설명 템플릿
# ─────────────────────────────────────────────
_DESC_TEMPLATE_KO = """{summary}

📌 이 영상은 AI가 자동으로 제작했습니다.
원본 출처: {url}

#AI영상 #자동생성 #지식정보"""

_DESC_TEMPLATE_EN = """{summary}

📌 This video was automatically created by AI.
Original source: {url}

#AIVideo #AutoGenerated #Knowledge"""

_SHORTS_TAG_KO = "#Shorts #쇼츠"
_SHORTS_TAG_EN = "#Shorts"

_DEFAULT_TAGS_KO = ["AI영상", "자동생성", "지식", "정보"]
_DEFAULT_TAGS_EN = ["AI", "AutoGenerated", "Knowledge", "Educational"]

# YouTube API 제한값
_MAX_TITLE_LEN = 100
_MAX_DESC_LEN = 5000
_MAX_TAGS = 30


def build_metadata(state: dict, lang: str = "ko", is_shorts: bool = False) -> dict[str, Any]:
    """
    YouTube videos.insert body dict를 생성한다.

    state:     pipeline.state
    lang:      "ko" | "en"
    is_shorts: 쇼츠 여부 (9:16 세로 영상)
    반환: {"snippet": {...}, "status": {...}}
    """
    import config

    title = _build_title(state, lang, is_shorts)
    description = _build_description(state, lang, is_shorts)
    tags = _build_tags(state, lang)

    metadata: dict[str, Any] = {
        "snippet": {
            "title": title[:_MAX_TITLE_LEN],
            "description": description[:_MAX_DESC_LEN],
            "tags": tags[:_MAX_TAGS],
            "categoryId": config.YOUTUBE_CATEGORY_ID,
            "defaultLanguage": "ko" if lang == "ko" else "en",
        },
        "status": {
            "privacyStatus": config.YOUTUBE_PRIVACY,
            "selfDeclaredMadeForKids": False,
        },
    }

    logger.debug(
        "[%s] 메타데이터 구성 완료 — 제목: %s / 태그: %d개",
        lang, title[:30], len(tags),
    )
    return metadata


# ─────────────────────────────────────────────
# 내부 헬퍼
# ─────────────────────────────────────────────

def _build_title(state: dict, lang: str, is_shorts: bool) -> str:
    """
    제목 구성.
    쇼츠는 #Shorts 접미사를 추가한다 (없는 경우에 한해).
    """
    title: str = state.get(f"youtube_title_{lang}") or "Untitled"

    if is_shorts:
        suffix = f" {_SHORTS_TAG_KO}" if lang == "ko" else f" {_SHORTS_TAG_EN}"
        if "#Shorts" not in title and "#shorts" not in title:
            max_base = _MAX_TITLE_LEN - len(suffix)
            title = title[:max_base] + suffix

    return title


def _build_description(state: dict, lang: str, is_shorts: bool) -> str:
    """
    설명 구성.
    Hook/core 장면 내레이션으로 요약을 만들고 출처 URL을 추가한다.
    """
    scenario = state.get(f"scenario_{lang}") or []
    url = state.get("url", "")
    summary = _extract_summary(scenario)

    template = _DESC_TEMPLATE_KO if lang == "ko" else _DESC_TEMPLATE_EN
    desc = template.format(summary=summary, url=url)

    if is_shorts:
        shorts_tag = _SHORTS_TAG_KO if lang == "ko" else _SHORTS_TAG_EN
        desc += f"\n{shorts_tag}"

    return desc


def _build_tags(state: dict, lang: str) -> list[str]:
    """
    태그 구성.
    제목 단어 + 기본 태그를 합산한다.
    """
    title: str = state.get(f"youtube_title_{lang}") or ""

    # 제목에서 단어 추출 (특수문자 제거, 2자 이상만)
    words = re.sub(r"[^\w\s가-힣]", "", title).split()
    title_tags = [w for w in words if len(w) >= 2]

    default_tags = _DEFAULT_TAGS_KO if lang == "ko" else _DEFAULT_TAGS_EN

    # 중복 없이 합산
    seen: set[str] = set()
    tags: list[str] = []
    for tag in title_tags + default_tags:
        if tag not in seen:
            seen.add(tag)
            tags.append(tag)

    return tags


def _extract_summary(scenario: list) -> str:
    """
    Hook → core 순서로 최대 3개 장면의 내레이션을 뽑아 요약 문장을 만든다.
    """
    priority = ("hook", "core", "problem")
    lines: list[str] = []

    for stage in priority:
        for scene in scenario:
            if scene.get("stage") == stage:
                narration = scene.get("narration", "").strip()
                if narration and narration not in lines:
                    lines.append(narration)
                    break
        if len(lines) >= 3:
            break

    # priority 스테이지에서 3개를 못 채우면 앞 장면으로 보충
    if len(lines) < 3:
        for scene in scenario:
            narration = scene.get("narration", "").strip()
            if narration and narration not in lines:
                lines.append(narration)
            if len(lines) >= 3:
                break

    return " ".join(lines).strip()
